'use client';

import { useState } from 'react';
import styles from './ZenNotes.module.scss';
import Image from 'next/image';
import ZenNoteHeroImg from '@/public/images/ZenNotes.svg';
import SOAPPreview from '@/public/images/soap-preview.svg';
import PatientNotesMobile from '@/public/images/patient-notes@2x.png';
import Layout from '@/components/Layout';

// ─── Types ────────────────────────────────────────────────────────────────────

interface FaqItem {
  q: string;
  a: string;
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const FEATURES = [
  {
    title: 'High-Fidelity Audio Tap',
    body: 'Uses a native WebRTC audio stream (owned by InstaGR/ZenSpace) rather than clunky external bots.',
  },
  {
    title: 'AI is the muscle. You are the soul.',
    body: 'The system simultaneously handles documentation, ICD-10 coding, and generating plain-language patient summaries.',
  },
  {
    title: 'Zero-Persistence Privacy.',
    body: 'Audio is processed in real-time and not permanently stored, adhering to the highest trust and HIPAA standards.',
  },
  {
    title: 'Human Final Signature.',
    body: 'Every note remains a draft until you authenticate it. You provide the soul.',
  },
];

const WORKDAY_ITEMS = [
  {
    label: 'Documentation — SOAP note drafting in real time',
    detail: null,
  },
  {
    label: 'Coding — ICD-10 and CPT codes assigned automatically',
    detail: null,
  },
  {
    label: 'Session and Patient Summaries — plain-language care plan sent immediately after the call',
    detail: null,
  },
];

const PRIVACY_BULLETS = [
  'No Meeting Bots.',
  'No Blood Audio.',
  'No Cloud Storage.',
  'Pure Actuation.',
];

const BILLING_BULLETS = [
  'No separate billing software.',
  'No manual entry.',
  'No pajama time invoicing.',
];

const FAQS: FaqItem[] = [
  {
    q: 'How is ZenSpace different from other AI note-takers?',
    a: 'Most AI tools are "wrappers" that rely on third-party bots like Zoom or Teams bots and store your data on their servers. ZenSpace is a Sovereign Infrastructure built on a custom, low-latency WebRTC stack. We own the data pipe, which means no third-party bots ever join your calls, and no data is ever "leaked" to external meeting platforms.',
  },
  {
    q: 'Does ZenSpace store audio recordings of my sessions?',
    a: 'No. We use Zero-Persistence RAM-Only processing. Clinical audio is streamed directly into our secure environment, processed in volatile memory (RAM), and then essentially "evaporated" once the session documentation is generated. We do not store audio files, and we do not use your sessions to train our AI models.',
  },
  {
    q: 'Is ZenSpace HIPAA compliant?',
    a: 'Yes. ZenSpace is built to exceed 2026 HIPAA and global data integrity standards. Because we own our infrastructure and utilize zero-persistence processing, we provide a level of security that legacy "cloud-storage" AI tools cannot match. We are a secure conduit for your clinical data, not a warehouse.',
  },
  {
    q: 'Who owns the clinical notes generated by ZenNotes?',
    a: 'You do. You have full ownership and control over all documentation. ZenNotes acts as your autonomous clinical assistant, drafting SOAP notes that are 95% complete by the time your session ends, but you remain the final authority and "Human-in-the-loop" for all clinical records.',
  },
  {
    q: 'How do you handle data during mobile-to-web handoffs?',
    a: 'We use our proprietary EZLink Deep-Routing Layer. This ensures that clinical intent and data persistence are maintained securely across devices without exposing sensitive information to insecure mobile clipboards or third-party linking services.',
  },
];

// ─── Sub-components ───────────────────────────────────────────────────────────

function ImagePlaceholder({ label }: { label: string }) {
  return (
    <div className={styles.imagePlaceholder}>
      <svg className={styles.placeholderIcon} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <rect x="3" y="3" width="18" height="18" rx="2" />
        <circle cx="8.5" cy="8.5" r="1.5" />
        <path d="M21 15l-5-5L5 21" />
      </svg>
      <span>{label}</span>
    </div>
  );
}

function FaqAccordion({ items }: { items: FaqItem[] }) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div className={styles.faqList}>
      {items.map((item, i) => {
        const isOpen = openIndex === i;
        return (
          <div className={styles.faqItem} key={i}>
            <button
              className={styles.faqQuestion}
              data-open={String(isOpen)}
              onClick={() => setOpenIndex(isOpen ? null : i)}
              aria-expanded={isOpen}
            >
              {item.q}
              <svg className={styles.faqChevron} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M6 9l6 6 6-6" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
            <div className={styles.faqAnswer} data-open={String(isOpen)} aria-hidden={!isOpen}>
              {item.a}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function ZenNotesPage() {
  return (
    <Layout>
      {/* ── Hero ── */}
      <section className={styles.hero}>
        <div className={styles.heroText}>
          <h1>
            Your session ends.<br />
            Your notes are<br />
            already <em>done.</em>
          </h1>
          <p>
            Capture every nuance without the Digital Wall. Our Ambient AI transcribes your soul,
            not just your computer audio.
          </p>
          <a href="#" className={styles.ctaButton}>
            Sign up for Alpha
          </a>
        </div>

        <div className={styles.heroImage}>
          {/* Replace with <Image src="/assets/zennotes-hero.png" alt="ZenNotes dashboard" fill /> */}
          <Image
            src={ZenNoteHeroImg}
            alt="ZenNotes dashboard"
          />
        </div>
      </section>

      {/* ── Trust Bar ── */}
      <section className={styles.trustBar}>
        <h2 className={styles.trustHeading}>Built for the most sensitive<br />conversations on earth.</h2>
        <p className={styles.trustSub}>Enter Ambient Clinical Intelligence (ACI).</p>

        <div className={styles.featuresGrid}>
          {FEATURES.map((f) => (
            <div className={styles.featureCard} key={f.title}>
              <h3>{f.title}</h3>
              <p>{f.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Workday Section ── */}
      <section className={styles.workdaySection}>
        <div className={styles.workdayText}>
          <h2>Say goodbye to 27-hour workday</h2>
          <p className={styles.workdaySub}>
            We guarantee 2 hours back every single day.
          </p>
          <ul className={styles.workdayList}>
            {WORKDAY_ITEMS.map((item, i) => (
              <li key={i}>
                <strong>{item.label}</strong>
              </li>
            ))}
          </ul>
        </div>

        <div className={styles.workdayImage}>
          {/* Replace with <Image src="/assets/zennotes-soap.png" alt="SOAP note preview" fill /> */}
          <Image src={SOAPPreview} alt="SOAP note preview" />
        </div>
      </section>

      {/* ── Privacy Section ── */}
      <section className={styles.privacySection}>
        <div className={styles.privacyInner}>
          <div className={styles.privacyPhone}>
            <div className={styles.phoneWrapper}>
              {/* Replace with <Image src="/assets/zennotes-call.png" alt="Call screen" fill /> */}
              <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#444" strokeWidth="1.5">
                <circle cx="12" cy="12" r="9" />
                <circle cx="12" cy="12" r="3" fill="#333" />
              </svg>
              <span style={{ color: '#555', fontSize: '0.7rem' }}>Phone UI — Calling screen</span>
            </div>
          </div>

          <div className={styles.privacyText}>
            <h2>Zero-Persistence. Total Privacy.</h2>
            <p className={styles.privacySub}>
              Unlike wrappers that store data in the cloud, ZenSpace uses RAM-only processing.
            </p>
            <ul className={styles.privacyBullets}>
              {PRIVACY_BULLETS.map((b) => (
                <li key={b}>{b}</li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* ── Public Notes Section ── */}
      <section className={styles.publicSection}>
        <div className={styles.publicText}>
          <h2>Private and public notes. Finally!</h2>
          <p className={styles.publicSub}>
            Your SOAP note stays yours — encrypted, HIPAA-compliant, audit-ready.
            Your patient gets context — names, team, actionable.
            Same session. Two truths. Both honored.
          </p>
        </div>

        <div className={styles.publicPhone}>
          <div className={styles.phoneard}>
            {/* Replace with <Image src="/assets/zennotes-phone-notes.png" alt="Patient notes on phone" fill /> */}
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="var(--color--grey2)" strokeWidth="1.5">
              <rect x="5" y="2" width="14" height="20" rx="2" />
              <line x1="9" y1="9" x2="15" y2="9" />
              <line x1="9" y1="13" x2="15" y2="13" />
              <line x1="9" y1="17" x2="12" y2="17" />
            </svg>
            {/* <span>Phone UI — Patient note view</span> */}
            <Image
              src={PatientNotesMobile}
              alt="Patient notes on phone" />
          </div>
        </div>
      </section>

      {/* ── Billing Section ── */}
      <section className={styles.billingSection}>
        <div className={styles.billingInner}>
          <h2>Your billing done before you close the laptop.</h2>
          <p>
            Automatically generates your SOAP note ZenNotes automatically generates a HIPAA-compliant superbill,
            CPT code, ICD-10, Session duration, Provider NPI. Ready to send to your patient in one click.
          </p>
          <ul className={styles.billingList}>
            {BILLING_BULLETS.map((b) => (
              <li key={b}>{b}</li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className={styles.faqSection}>
        <h2>FAQ</h2>
        <FaqAccordion items={FAQS} />
      </section>


    </Layout>
  );
}
