'use client';
import { useState } from "react";

const faqs = [
  [
    'How is Zenspace different from other AI note-takers?',
    'Most AI tools are "wrappers" that rely on third-party bots like Zoom or Teams bots and store your data on their servers. ZenSpace is a Sovereign Infrastructure built on a custom, low-latency WebRTC stack. We own the data pipe, which means no third-party bots ever join your calls, and no data is ever "leaked" to external meeting platforms.',
  ],
  [
    'Does Zenspace store audio recordings of my sessions?',
    'No. We use Zero-Persistence RAM-Only processing. Clinical audio is streamed directly into our secure environment, processed in volatile memory (RAM), and then essentially "evaporated" once the session documentation is generated. We do not store audio files, and we do not use your sessions to train our AI models.',
  ],
  [
    'Is Zenspace HIPAA compliant?',
    'Yes. ZenSpace is built to exceed 2026 HIPAA and global data integrity standards. Because we own our infrastructure and utilize zero-persistence processing, we provide a level of security that legacy "cloud-storage" AI tools cannot match. We are a secure conduit for your clinical data, not a warehouse.',
  ],
  [
    'Who owns the clinical notes generated by ZenNotes?',
    'You do. You have full ownership and control over all documentation. ZenNotes acts as your autonomous clinical assistant, drafting SOAP notes that are 95% complete by the time your session ends, but you remain the final authority and "Human-in-the-loop" for all clinical records.',
  ],
  [
    'How do you handle data during mobile-to-web handoffs?',
    'We use our proprietary EZLink Deep-Routing Layer. This ensures that clinical intent and data persistence are maintained securely across devices without exposing sensitive information to insecure mobile clipboards or third-party linking services.',
  ],
  ];

export default function ZenNotesFAQ() {

  const [selIdx, setIndex] = useState<number | null>();

  // ref.current
  const expandAnswer = (idx : null | number) => {
    if (selIdx === idx) {      
      setIndex(null)
    } else {
      setIndex(idx)
    }  
  }

  return <section id="faqs">
      <div className='container'>
        <div>
          <h2 className="u-textcenter mb-6" style={{marginBottom: "32px"}}>
            Privacy and Trust Questions?
          </h2>

          <div>
          {faqs.map((faq, idx) => (
            <div
              className="expandable-single-faq"
              key={idx}
              onClick={() => expandAnswer(idx)}
            >
              <div className="expandable-top">
                <div className="heading-expandable">
                  {faq[0]}
                </div>
                <div className="expandable-icon">
                  {selIdx === idx ? "-" : "+"}
                </div>
              </div>
              <div className={selIdx === idx ? "expandable-bottom open" : "expandable-bottom"}>
                <div className="faq-paragraph">
                  {faq[1]}
                </div>
              </div>
            </div>
          ))}
          </div>
        </div>
      </div>
    </section>
}